source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     ['./_scss/*.*']

permalink: /:title

# url: http://glen.local:4000
# url: http://localhost:4000
url: http://vestride.github.io/Shuffle

defaultTitle: 'Shuffle.js'
defaultDescription: 'Categorize, sort, and filter a responsive grid of items'
defaultImage: '/img/hero.png'

demos:
  - url: 'demos/2013-05-01-basic'
    slug: basic
    label: Basic masonry layout
    screenshot: basic.webp
  - url: 'demos/2013-06-19-adding-removing'
    slug: adding-removing
    label: Adding and removing items
    screenshot: removing.webp
  - url: 'demos/2013-05-02-adaptive'
    slug: adaptive
    label: Adaptive bootstrap grid with compound filters
    screenshot: adaptive.webp
  - url: 'demos/2013-05-03-images'
    slug: images
    label: Using images
    screenshot: images.webp

shapes:
  - shape: circle
    color: blue
  - shape: diamond
    color: red
  - shape: triangle
    color: green
  - shape: triangle
    color: orange
  - shape: square
    color: red
  - shape: diamond
    color: green
  - shape: circle
    color: red
  - shape: square
    color: green
  - shape: circle
    color: orange
  - shape: diamond
    color: blue
  - shape: square
    color: orange
  - shape: square
    color: blue

items:
  - groups: [ photography ]
    date: 2010-09-14
    title: Baseball
    img: baseball.png
    original: baseball.jpg
    cols: 3
  - groups: [ wallpaper, 3d ]
    date: 2011-08-14
    title: Tennis
    img: tennis-ball.png
    original: tennis-ball.jpg
    description: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
    cols: 6
  - groups: [ wallpaper, 3d ]
    date: 2009-05-27
    title: iMac
    img: imac.png
    original: imac.jpg
    cols: 3
  - groups: [ graphics ]
    date: 2012-05-14
    title: Master Chief
    img: master-chief.png
    original: Master_Chief_Portrait_by_Eightfold_Studios.jpg
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
    extras: [ h2 ]
    cols: 3
  - groups: [ wallpaper, 3d ]
    date: 2009-09-14
    title: Eightfold
    img: es-blue.png
    original: es-blue.jpg
    cols: 3
  - groups: [ photography ]
    date: 2012-03-14
    title: Pumpkin
    img: pumpkin.png
    original: pumpkin.jpg
    description: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
    cols: 6
  - groups: [ wallpaper, 3d ]
    date: 2013-05-19
    title: Vestride
    img: vestride-red.png
    original: vestride-red.jpg
    extras: [ h2 ]
    cols: 6
  - groups: [ graphics ]
    date: 2013-02-01
    title: Newegg
    img: newegg.png
    original: newegg.jpg
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
    extras: [ h2 ]
    cols: 3
  - groups: [ wallpaper ]
    date: 2000-01-01
    title: Arc
    img: eightfoldarc.png
    original: eightfoldarc.jpg
    cols: 3
  - groups: [ photography ]
    date: 2012-07-04
    title: Ground
    img: ground.png
    original: ground!.jpg
    cols: 3
  - groups: [ wallpaper ]
    date: 2011-08-12
    title: Grass
    img: grassy-hills.png
    original: grassy-hills.tif
    description: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
    cols: 6
  - groups: [ wallpaper, 3d ]
    date: 2013-05-19
    title: Vestride
    img: vestride-classy.png
    original: vestride-classy.jpg
    cols: 3


